/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Authorize
         * @description Return the Google OAuth consent page URL.
         *
         *     The frontend should redirect the user to this URL.
         *     After consent, Google redirects to GOOGLE_REDIRECT_URI with ?code=...
         */
        get: operations["google_authorize_api_v1_auth_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Callback
         * @description Exchange Google authorization code for tokens, create/link user, return JWT.
         *
         *     This endpoint receives the redirect from Google after the user approves
         *     the OAuth consent screen. It:
         *     1. Exchanges the code for access + refresh tokens
         *     2. Fetches the user's Google profile (email, name, google_id)
         *     3. Creates a new Orchestruct account OR links to an existing one
         *     4. Returns a JWT in the same format as /auth/login
         *
         *     The frontend can treat this response identically to a normal login.
         */
        get: operations["google_callback_api_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_api_v1_goals_get"];
        put?: never;
        /** Create Goal */
        post: operations["create_goal_api_v1_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal */
        get: operations["get_goal_api_v1_goals__goal_id__get"];
        put?: never;
        post?: never;
        /** Delete Goal */
        delete: operations["delete_goal_api_v1_goals__goal_id__delete"];
        options?: never;
        head?: never;
        /** Update Goal */
        patch: operations["update_goal_api_v1_goals__goal_id__patch"];
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Task */
        get: operations["list_task_api_v1_goals__goal_id__tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_goals__goal_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_goals__goal_id__tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_api_v1_goals__goal_id__tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_api_v1_goals__goal_id__tasks__task_id__patch"];
        trace?: never;
    };
    "/api/v1/plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Plan
         * @description Generate a new plan for the current user or a team.
         *
         *     For user plans: scope defaults to current user.
         *     For team plans: current user must be a team member.
         */
        post: operations["create_plan_api_v1_plans_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_v1_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Approve */
        post: operations["plan_approve_api_v1_plans__plan_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Reject */
        post: operations["plan_reject_api_v1_plans__plan_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Get the current user's schedule configuration.
         */
        get: operations["get_config_api_v1_calendar_config_get"];
        /**
         * Update Config
         * @description Update schedule configuration for the current user.
         */
        put: operations["update_config_api_v1_calendar_config_put"];
        /**
         * Create Config
         * @description Create schedule configuration for the current user.
         */
        post: operations["create_config_api_v1_calendar_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description List calendar events within a date range.
         */
        get: operations["list_events_api_v1_calendar_events_get"];
        put?: never;
        /**
         * Create Event
         * @description Create a new calendar event.
         */
        post: operations["create_event_api_v1_calendar_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event
         * @description Get a single calendar event.
         */
        get: operations["get_event_api_v1_calendar_events__event_id__get"];
        /**
         * Update Event
         * @description Update a calendar event.
         */
        put: operations["update_event_api_v1_calendar_events__event_id__put"];
        post?: never;
        /**
         * Delete Event
         * @description Delete a calendar event.
         */
        delete: operations["delete_event_api_v1_calendar_events__event_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/events/{event_id}/skip/{skip_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip Occurrence
         * @description Skip a specific occurrence of a recurring event.
         */
        post: operations["skip_occurrence_api_v1_calendar_events__event_id__skip__skip_date__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Availability
         * @description Get free/busy availability grid for a date range.
         */
        get: operations["get_availability_api_v1_calendar_availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/availability/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Availability Summary
         * @description Get availability summary statistics for a date range.
         */
        get: operations["get_availability_summary_api_v1_calendar_availability_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worklogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Worklogs */
        get: operations["list_worklogs_api_v1_worklogs_get"];
        put?: never;
        /** Create Worklog */
        post: operations["create_worklog_api_v1_worklogs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worklogs/{worklog_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Worklog */
        get: operations["get_worklog_api_v1_worklogs__worklog_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Metrics
         * @description Return current user's behavioral features, recomputing if stale (>1 day).
         */
        get: operations["get_my_metrics_api_v1_metrics_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/alignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alignment Score
         * @description Return alignment score for the given week window.
         */
        get: operations["get_alignment_score_api_v1_metrics_alignment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nudges/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Nudges
         * @description Run nudge evaluation for the current user. Returns newly created nudges.
         */
        post: operations["evaluate_nudges_api_v1_nudges_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nudges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Nudges
         * @description List nudges for the current user, optionally filtered by status.
         */
        get: operations["list_nudges_api_v1_nudges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nudges/{nudge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Nudge */
        get: operations["get_nudge_api_v1_nudges__nudge_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nudges/{nudge_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge Nudge */
        post: operations["acknowledge_nudge_api_v1_nudges__nudge_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nudges/{nudge_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Nudge */
        post: operations["dismiss_nudge_api_v1_nudges__nudge_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_v1_teams_get"];
        put?: never;
        /** Create Team */
        post: operations["create_team_api_v1_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team */
        get: operations["get_team_api_v1_teams__team_id__get"];
        put?: never;
        post?: never;
        /** Delete Team */
        delete: operations["delete_team_api_v1_teams__team_id__delete"];
        options?: never;
        head?: never;
        /** Update Team */
        patch: operations["update_team_api_v1_teams__team_id__patch"];
        trace?: never;
    };
    "/api/v1/teams/{team_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_v1_teams__team_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_api_v1_teams__team_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v1_teams__team_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Transcript */
        post: operations["upload_transcript_api_v1_meetings_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_api_v1_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Transcript */
        post: operations["apply_transcript_api_v1_meetings__meeting_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItemOut */
        ActionItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Raw Text */
            raw_text: string;
            /** Assigned To User Id */
            assigned_to_user_id: string | null;
            /** Priority */
            priority: number;
            /** Estimated Hours */
            estimated_hours: number | null;
            /** Task Id */
            task_id: string | null;
        };
        /** AddMemberRequest */
        AddMemberRequest: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** AlignmentScoreResponse */
        AlignmentScoreResponse: {
            /** Plan Items */
            plan_items: number;
            /** Logged Tasks */
            logged_tasks: number;
            /** Alignment Score */
            alignment_score: number;
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /**
             * Week End
             * Format: date
             */
            week_end: string;
        };
        /** AvailabilityGridResponse */
        AvailabilityGridResponse: {
            /** Days */
            days: components["schemas"]["DayAvailabilityResponse"][];
            /** Summary */
            summary: Record<string, never>;
        };
        /** AvailabilitySummaryResponse */
        AvailabilitySummaryResponse: {
            /** Work Days */
            work_days: number;
            /** Total Work Hours */
            total_work_hours: number;
            /** Total Busy Hours */
            total_busy_hours: number;
            /** Total Free Hours */
            total_free_hours: number;
            /** Utilization Percent */
            utilization_percent: number;
        };
        /** CalendarEventCreate */
        CalendarEventCreate: {
            schedule_type: components["schemas"]["ScheduleType"];
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Start Datetime
             * Format: date-time
             */
            start_datetime: string;
            /**
             * End Datetime
             * Format: date-time
             */
            end_datetime: string;
            /**
             * All Day
             * @default false
             */
            all_day: boolean;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /** Rrule */
            rrule?: string | null;
        };
        /** CalendarEventResponse */
        CalendarEventResponse: {
            schedule_type: components["schemas"]["ScheduleType"];
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Start Datetime
             * Format: date-time
             */
            start_datetime: string;
            /**
             * End Datetime
             * Format: date-time
             */
            end_datetime: string;
            /**
             * All Day
             * @default false
             */
            all_day: boolean;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /** Rrule */
            rrule?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Is Recurring */
            is_recurring: boolean;
            /** Recurrence End */
            recurrence_end: string | null;
            /** Exdates */
            exdates: string[] | null;
            /** Parent Event Id */
            parent_event_id: string | null;
            /** External Id */
            external_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CalendarEventUpdate */
        CalendarEventUpdate: {
            schedule_type?: components["schemas"]["ScheduleType"] | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Start Datetime */
            start_datetime?: string | null;
            /** End Datetime */
            end_datetime?: string | null;
            /** All Day */
            all_day?: boolean | null;
            /** Timezone */
            timezone?: string | null;
            /** Rrule */
            rrule?: string | null;
        };
        /** DayAvailabilityResponse */
        DayAvailabilityResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            work_hours: components["schemas"]["TimeSlotResponse"] | null;
            /** Busy Slots */
            busy_slots: components["schemas"]["TimeSlotResponse"][];
            /** Free Slots */
            free_slots: components["schemas"]["TimeSlotResponse"][];
        };
        /** GoalCreate */
        GoalCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** @default user */
            scope_type: components["schemas"]["ScopeType"];
            /** Scope Id */
            scope_id?: string | null;
            /** Success Metric Type */
            success_metric_type?: string | null;
            /** Target Value */
            target_value?: number | null;
            /** Target Date */
            target_date?: string | null;
            /**
             * Priority Weight
             * @default 1
             */
            priority_weight: number;
            /** Min Weekly Hours */
            min_weekly_hours?: number | null;
            /** Max Weekly Hours */
            max_weekly_hours?: number | null;
            /** Constraints */
            constraints?: Record<string, never> | null;
        };
        /** GoalResponse */
        GoalResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            scope_type: components["schemas"]["ScopeType"];
            /**
             * Scope Id
             * Format: uuid
             */
            scope_id: string;
            /** Success Metric Type */
            success_metric_type: string | null;
            /** Target Value */
            target_value: number | null;
            /** Target Date */
            target_date: string | null;
            /** Priority Weight */
            priority_weight: number;
            /** Min Weekly Hours */
            min_weekly_hours: number | null;
            /** Max Weekly Hours */
            max_weekly_hours: number | null;
            /** Constraints */
            constraints: Record<string, never> | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GoalUpdate */
        GoalUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Success Metric Type */
            success_metric_type?: string | null;
            /** Target Value */
            target_value?: number | null;
            /** Target Date */
            target_date?: string | null;
            /** Priority Weight */
            priority_weight?: number | null;
            /** Min Weekly Hours */
            min_weekly_hours?: number | null;
            /** Max Weekly Hours */
            max_weekly_hours?: number | null;
            /** Constraints */
            constraints?: Record<string, never> | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeetingApplyRequest */
        MeetingApplyRequest: {
            /**
             * Goal Id
             * Format: uuid
             */
            goal_id: string;
            /** Action Item Ids */
            action_item_ids?: string[] | null;
        };
        /** MeetingTranscriptOut */
        MeetingTranscriptOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Title */
            title: string | null;
            /** Source */
            source: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /**
             * Action Items
             * @default []
             */
            action_items: components["schemas"]["ActionItemOut"][];
        };
        /** MeetingUploadRequest */
        MeetingUploadRequest: {
            /** Title */
            title?: string | null;
            /** Transcript Text */
            transcript_text: string;
            /** Source */
            source?: string | null;
        };
        /** MemberResponse */
        MemberResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Is Admin */
            is_admin: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NudgeResponse */
        NudgeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Nudge Type */
            nudge_type: string;
            /** Message */
            message: string;
            /** Trigger Data */
            trigger_data: Record<string, never> | null;
            /** Status */
            status: string;
            /** Acknowledged At */
            acknowledged_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PlanGenerate */
        PlanGenerate: {
            /**
             * Planning Window Start
             * Format: date
             */
            planning_window_start: string;
            /**
             * Planning Window End
             * Format: date
             */
            planning_window_end: string;
            /** @default user */
            scope_type: components["schemas"]["ScopeType"];
            /** Scope Id */
            scope_id?: string | null;
        };
        /** PlanItemResponse */
        PlanItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /**
             * End Time
             * Format: time
             */
            end_time: string;
            /** Risk Score */
            risk_score: number | null;
            /** Rationale */
            rationale: Record<string, never> | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Assigned To User Id */
            assigned_to_user_id?: string | null;
        };
        /** PlanResponse */
        PlanResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            scope_type: components["schemas"]["ScopeType"];
            /**
             * Scope Id
             * Format: uuid
             */
            scope_id: string;
            /**
             * Planning Window Start
             * Format: date
             */
            planning_window_start: string;
            /**
             * Planning Window End
             * Format: date
             */
            planning_window_end: string;
            /** Status */
            status: string;
            /** Risk Summary */
            risk_summary: Record<string, never> | null;
            /** Items */
            items: components["schemas"]["PlanItemResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScheduleConfigCreate */
        ScheduleConfigCreate: {
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Work Days
             * @default [
             *       0,
             *       1,
             *       2,
             *       3,
             *       4
             *     ]
             */
            work_days: number[];
            /**
             * Work Start Time
             * Format: time
             * @default 09:00:00
             */
            work_start_time: string;
            /**
             * Work End Time
             * Format: time
             * @default 17:00:00
             */
            work_end_time: string;
            /** Day Overrides */
            day_overrides?: Record<string, never> | null;
        };
        /** ScheduleConfigResponse */
        ScheduleConfigResponse: {
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Work Days
             * @default [
             *       0,
             *       1,
             *       2,
             *       3,
             *       4
             *     ]
             */
            work_days: number[];
            /**
             * Work Start Time
             * Format: time
             * @default 09:00:00
             */
            work_start_time: string;
            /**
             * Work End Time
             * Format: time
             * @default 17:00:00
             */
            work_end_time: string;
            /** Day Overrides */
            day_overrides?: Record<string, never> | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScheduleConfigUpdate */
        ScheduleConfigUpdate: {
            /** Timezone */
            timezone?: string | null;
            /** Work Days */
            work_days?: number[] | null;
            /** Work Start Time */
            work_start_time?: string | null;
            /** Work End Time */
            work_end_time?: string | null;
            /** Day Overrides */
            day_overrides?: Record<string, never> | null;
        };
        /**
         * ScheduleType
         * @enum {string}
         */
        ScheduleType: "work" | "personal" | "blocked";
        /**
         * ScopeType
         * @enum {string}
         */
        ScopeType: "user" | "team" | "org";
        /** TaskCreate */
        TaskCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Estimated Minutes */
            estimated_minutes?: number | null;
            /** Difficulty */
            difficulty?: number | null;
            /** Due Date */
            due_date?: string | null;
            /**
             * Dislike Score
             * @default 0
             */
            dislike_score: number;
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Prerequisites */
            prerequisites?: unknown[] | null;
        };
        /** TaskResponse */
        TaskResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Goal Id
             * Format: uuid
             */
            goal_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Estimated Minutes */
            estimated_minutes: number | null;
            /** Difficulty */
            difficulty: number | null;
            /** Due Date */
            due_date: string | null;
            /** Dislike Score */
            dislike_score: number;
            /** Owner User Id */
            owner_user_id: string | null;
            /** Prerequisites */
            prerequisites: unknown[] | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TaskUpdate */
        TaskUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Estimated Minutes */
            estimated_minutes?: number | null;
            /** Difficulty */
            difficulty?: number | null;
            /** Due Date */
            due_date?: string | null;
            /** Dislike Score */
            dislike_score?: number | null;
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Prerequisites */
            prerequisites?: unknown[] | null;
            /** Status */
            status?: string | null;
        };
        /** TeamCreate */
        TeamCreate: {
            /** Name */
            name: string;
        };
        /** TeamResponse */
        TeamResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Organization Id */
            organization_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TeamUpdate */
        TeamUpdate: {
            /** Name */
            name?: string | null;
        };
        /** TimeSlotResponse */
        TimeSlotResponse: {
            /**
             * Start
             * Format: time
             */
            start: string;
            /**
             * End
             * Format: time
             */
            end: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
        };
        /** UserFeaturesResponse */
        UserFeaturesResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Completion Rate */
            completion_rate: number;
            /** Estimation Bias Multiplier */
            estimation_bias_multiplier: number;
            /** Focus Probability By Hour */
            focus_probability_by_hour: Record<string, never> | null;
            /** Reschedule Rate */
            reschedule_rate: number;
            /** Burnout Score */
            burnout_score: number;
            /** Last Computed At */
            last_computed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Superuser */
            is_superuser: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkLogCreate */
        WorkLogCreate: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /** Notes */
            notes?: string | null;
        };
        /** WorkLogResponse */
        WorkLogResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Completed */
            completed: boolean;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    google_authorize_api_v1_auth_google_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_callback_api_v1_auth_google_callback_get: {
        parameters: {
            query: {
                code: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_api_v1_goals_get: {
        parameters: {
            query?: {
                team_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_goal_api_v1_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goal_api_v1_goals__goal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_goal_api_v1_goals__goal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_goal_api_v1_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_task_api_v1_goals__goal_id__tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_goals__goal_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_goals__goal_id__tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_v1_goals__goal_id__tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_v1_goals__goal_id__tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_v1_plans_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanGenerate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_v1_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_approve_api_v1_plans__plan_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_reject_api_v1_plans__plan_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_v1_calendar_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleConfigResponse"];
                };
            };
        };
    };
    update_config_api_v1_calendar_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_config_api_v1_calendar_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleConfigCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_calendar_events_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_v1_calendar_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_calendar_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_api_v1_calendar_events__event_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarEventUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_event_api_v1_calendar_events__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_occurrence_api_v1_calendar_events__event_id__skip__skip_date__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
                skip_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_availability_api_v1_calendar_availability_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityGridResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_availability_summary_api_v1_calendar_availability_summary_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilitySummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_worklogs_api_v1_worklogs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkLogResponse"][];
                };
            };
        };
    };
    create_worklog_api_v1_worklogs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_worklog_api_v1_worklogs__worklog_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worklog_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_metrics_api_v1_metrics_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFeaturesResponse"];
                };
            };
        };
    };
    get_alignment_score_api_v1_metrics_alignment_get: {
        parameters: {
            query: {
                week_start: string;
                week_end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlignmentScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_nudges_api_v1_nudges_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NudgeResponse"][];
                };
            };
        };
    };
    list_nudges_api_v1_nudges_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NudgeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nudge_api_v1_nudges__nudge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nudge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NudgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_nudge_api_v1_nudges__nudge_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nudge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NudgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_nudge_api_v1_nudges__nudge_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nudge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NudgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_v1_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"][];
                };
            };
        };
    };
    create_team_api_v1_teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_api_v1_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_team_api_v1_teams__team_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_api_v1_teams__team_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_teams__team_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_v1_teams__team_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_teams__team_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_transcript_api_v1_meetings_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingTranscriptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_v1_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingTranscriptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_transcript_api_v1_meetings__meeting_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
